
include SLAM/gmapping/utils/Makefile
include SLAM/gmapping/log/Makefile
include SLAM/gmapping/sensor/Makefile
include SLAM/gmapping/scanmatcher/Makefile
include SLAM/gmapping/configfile/Makefile
#include SLAM/gmapping/gfs-j2b2/Makefile
include SLAM/gmapping/gridfastslam/Makefile

